version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: chat_app
    ports:
      - "5432:5432"
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: chat_app
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
